{
 "title": "System overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgw_pkgs", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd\", name=\"prometheus.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ 4" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{job=\"systemd\", name=\"prometheus-systemd-exporter.service\", state=\"active\"}) + \r\nsum(systemd_unit_state{job=\"systemd\", name=\"prometheus-node-exporter.service\", state=\"active\"}) + \r\nsum(systemd_unit_state{job=\"systemd\", name=\"pgw_exporter.timer\", state=\"active\"}) +\r\nsum(systemd_unit_state{job=\"systemd\", name=\"pgw_pkgs.service\", state=\"inactive\"} OR \r\nsystemd_unit_state{job=\"systemd\", name=\"pgw_pkgs.service\", state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "syslog-ng",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd\", name=\"syslog-ng@default.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Telegraf",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd\", name=\"telegraf.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd\", name=\"influxdb.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MariaDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd\", name=\"mariadb.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rlpi",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd\", name=\"rlpi.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logrotate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{job=\"systemd\", name=\"logrotate.service\", state=\"inactive\"} OR \r\nsystemd_unit_state{job=\"systemd\", name=\"logrotate.service\", state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logrotate.timer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((time() - systemd_timer_last_trigger_seconds{name='logrotate.timer'}) / 3600, 0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} )  / (node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgw_process_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logging Rate (InfluxDB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "pgw_pinger", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10, pgw_cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10, pgw_mem_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SDcard read/write activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device='mmcblk1'}[5m]) / rate(node_disk_reads_completed_total{device='mmcblk1'}[5m])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{device='mmcblk1'}[5m]) / rate(node_disk_writes_completed_total{device='mmcblk1'}[5m])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}